#!/bin/sh
# A script for eww (elkowar's wacky widget) to show the current month.
# Maintained by humanwhodebugs

# Current month as a two-digit number (01-12)
MONTH=$(date +%m)

# Output the month
echo $MONTH
